### PR TITLE
Fixed an error when the first test is skipped

### PR DESCRIPTION
**Pull request by f213**
This fixes https://github.com/getsentry/pytest-responses/issues/10

### CODE REVIEW

**Comment by stuaxo** [comment]
Hi @getsentry this fix works for me, any chance of merging + doing a release ?

**Review by stuaxo — APPROVED** [review]
This works for me.

**Review by stuaxo — APPROVED** [review]
Works for me :)

**Comment by chadwhitacre** [comment]
Merging, will follow up with some minor tweaks.

**Review by chadwhitacre — APPROVED** [review]
I can repro #10 and the fix here works. Would like to see a test, and this doesn't pass the linter. Will follow up with those separately ...

**Comment by VVyacheslav** [comment]
Is there any chance of this merging?

**Comment by chadwhitacre** [comment]
Merged! Test added in #13.

Next chance I get I will work on cutting a new release, ticketed as #19.

**Comment by stuaxo** [comment]
Awesome, thanks for looking at this :)

**Comment by chadwhitacre** [comment]
[0.5.0 is out](https://pypi.org/project/pytest-responses/)! Thanks for your patience. 🙇‍♂️

**Pull request merged**
